MODULE MPL_DOUBLESTACK_MOD

USE FIAT_DOUBLESTACK_MOD
USE ISO_C_BINDING, ONLY : C_INT8_T

IMPLICIT NONE

TYPE(FIAT_DOUBLESTACK), SAVE :: MPL_DOUBLESTACK
INTEGER(KIND=C_INT8_T), PARAMETER :: MPL_LOWER=0
INTEGER(KIND=C_INT8_T), PARAMETER :: MPL_UPPER=1

CONTAINS

SUBROUTINE DOUBLESTACK_INIT(LDGPU)
  LOGICAL, INTENT(IN), OPTIONAL :: LDGPU
  LOGICAL :: LLGPU
  CHARACTER(LEN=32)  :: CL_MPL_DOUBLESTACK_SIZE
  INTEGER*8          :: IL_MPL_DOUBLESTACK_SIZE
  INTEGER*8          :: ILEN

  IF (PRESENT(LDGPU)) THEN
    LLGPU=LDGPU
  ELSE
    LLGPU=.FALSE.
  ENDIF
  
  CALL GET_ENVIRONMENT_VARIABLE('MPL_DOUBLESTACK_SIZE',CL_MPL_DOUBLESTACK_SIZE)
  
  IF (CL_MPL_DOUBLESTACK_SIZE /= '') THEN
    ILEN = LEN_TRIM (CL_MPL_DOUBLESTACK_SIZE)
    IF (CL_MPL_DOUBLESTACK_SIZE (ILEN-1:ILEN) == 'MB') THEN
      READ (CL_MPL_DOUBLESTACK_SIZE (1:ILEN-2), *) IL_MPL_DOUBLESTACK_SIZE
      IL_MPL_DOUBLESTACK_SIZE = IL_MPL_DOUBLESTACK_SIZE * 1024_8**2
    ELSEIF (CL_MPL_DOUBLESTACK_SIZE (ILEN-1:ILEN) == 'GB') THEN
      READ (CL_MPL_DOUBLESTACK_SIZE (1:ILEN-2), *) IL_MPL_DOUBLESTACK_SIZE
      IL_MPL_DOUBLESTACK_SIZE = IL_MPL_DOUBLESTACK_SIZE * 1024_8**3
    ELSE
      CALL ABOR1 ('MPL_DOUBLESTACK_SIZE : UNEXPECTED VALUE '//TRIM (CL_MPL_DOUBLESTACK_SIZE))
    ENDIF 
    WRITE (0, *) " MPL_DOUBLESTACK_SIZE = ", CL_MPL_DOUBLESTACK_SIZE
    CALL MPL_DOUBLESTACK%INIT (IL_MPL_DOUBLESTACK_SIZE,LLGPU)
  ELSE
    IL_MPL_DOUBLESTACK_SIZE=256*1024_8**2
    CALL MPL_DOUBLESTACK%INIT(IL_MPL_DOUBLESTACK_SIZE,LLGPU)
  ENDIF

END SUBROUTINE DOUBLESTACK_INIT


END MODULE MPL_DOUBLESTACK_MOD
